version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: money_tracing_service
    environment:
      POSTGRES_DB: moneytracingdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: 